spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://localhost:8080/realms/Scepter
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: ebuka-rest-api
      principal-attribute: preferred_username